5-5-2023/masterpeace2/masterpeace2/Controllers/ResturantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using masterpeace2;
using Microsoft.AspNet.Identity;

namespace masterpeace2.Controllers
{
    public class ResturantsController : Controller
    {
        private masterpeaceEntities1 db = new masterpeaceEntities1();

        // GET: Resturants
        public ActionResult Index()
        {
            var resturants = db.Resturants.Include(r => r.AspNetUser);
            return View(resturants.ToList());
        }

        // GET: Resturants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resturant resturant = db.Resturants.Find(id);
            if (resturant == null)
            {
                return HttpNotFound();
            }
            return View(resturant);
        }

        // GET: Resturants/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Resturants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,UserId,Name,Address,PhoneNumber,Image")] Resturant resturant)
        {
            if (ModelState.IsValid)
            {
                db.Resturants.Add(resturant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", resturant.UserId);
            return View(resturant);
        }

        // GET: Resturants/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resturant resturant = db.Resturants.Find(id);
             Session["img"] = resturant.Image;
            if (resturant == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", resturant.UserId);
            return View(resturant);
        }

        // POST: Resturants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserId,Name,Address,PhoneNumber,Image")] Resturant resturant, HttpPostedFileBase ImageFile1)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile1 != null && ImageFile1.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(ImageFile1.FileName);
                    var path = Path.Combine(Server.MapPath("~/photos for masterpeace/"), fileName);
                    if (!Directory.Exists(Server.MapPath("~/photos for masterpeace/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/photos for masterpeace/"));
                    }
                    ImageFile1.SaveAs(path);
                    resturant.Image = fileName; // Set the category image property to the uploaded file name
                }
                else if (ImageFile1 == null)
                {
                    resturant.Image = Session["img"].ToString();
                }

                db.Entry(resturant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", resturant.UserId);
            return View(resturant);
        }

        // GET: Resturants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resturant resturant = db.Resturants.Find(id);
            if (resturant == null)
            {
                return HttpNotFound();
            }
            return View(resturant);
        }

        // POST: Resturants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Resturant resturant = db.Resturants.Find(id);
            db.Resturants.Remove(resturant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //public ActionResult resInfo(string x)
        //{
        //    //var resid = User.Identity.GetUserId(); 
        //    //var resturant = db.Resturants.Where(r => r.UserId== resid);
        //    return View(x);
        //}
        public ActionResult ResInfo()
        {
            var id = User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //AspNetUser user = db.AspNetUsers.Find(id);
            Resturant rest = db.Resturants.Where(o=>o.UserId== id).FirstOrDefault();
            if (rest == null)
            {
                return HttpNotFound();
            }
            return View(rest);
        }

        public ActionResult Restproduct()
        {
            var id = User.Identity.GetUserId();
            //var products = db.Products.Include(p => p.Category).Include(p => p.Resturant).Where(p=>p.r);
            var products = db.Products.Where(p=>p.Resturant.UserId== id);
            return View("Restproduct",products.ToList());
        }

        public ActionResult RestCreate()
        {
            ViewBag.Category_ID = new SelectList(db.Categories, "ID", "Category_Name");
            ViewBag.ResturantID = new SelectList(db.Resturants, "ID", "UserId");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResCreate([Bind(Include = "ID,Product_Name,Category_ID,Price,ResturantID,Image1,Image2,Image3,Image4")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Category_ID = new SelectList(db.Categories, "ID", "Category_Name", product.Category_ID);
            ViewBag.ResturantID = new SelectList(db.Resturants, "ID", "UserId", product.ResturantID);
            return View(product);
        }







        public ActionResult RestOrders()
        {
            var id = User.Identity.GetUserId();
            //var products = db.Products.Include(p => p.Category).Include(p => p.Resturant).Where(p=>p.r);
            var orders = db.Orders.Where(p=>p.Product.Resturant.UserId==id& p.IsAccepted==null);
            return View("RestOrders", orders.ToList());
        }

        public ActionResult AcceptOrders(int id)
        {
            var ID = User.Identity.GetUserId();
            //var products = db.Products.Include(p => p.Category).Include(p => p.Resturant).Where(p=>p.r);
            var allorders = db.Orders.Where(p => p.Product.Resturant.UserId == ID & p.IsAccepted == null);
            var orders = db.Orders.Find(id);
            orders.IsAccepted = true;
            db.SaveChanges();
            //var orders = db.Orders.Where(p => p.ID==id).Select(p => p.Status);
            //orders.status
            return View("RestOrders",allorders);
        }

        public ActionResult RejectOrders(int id)
        {
            var ID = User.Identity.GetUserId();
            //var products = db.Products.Include(p => p.Category).Include(p => p.Resturant).Where(p=>p.r);
            var allorders = db.Orders.Where(p => p.Product.Resturant.UserId == ID & p.IsAccepted == null);
            var orders = db.Orders.Find(id);
            orders.IsAccepted = false;
            db.SaveChanges();
            //var orders = db.Orders.Where(p => p.ID==id).Select(p => p.Status);
            //orders.status
            return View("RestOrders", allorders);
        }

        public ActionResult AcceptedOrders()
        {
            var id = User.Identity.GetUserId();
            //var products = db.Products.Include(p => p.Category).Include(p => p.Resturant).Where(p=>p.r);
            var orders = db.Orders.Where(p => p.Product.Resturant.UserId == id & p.IsAccepted == true);
            return View( orders.ToList());
        }


    }
}

5-5-2023/masterpeace2/masterpeace2/Views/Resturants/Create.cshtml
@model masterpeace2.Resturant

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdminDash.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Resturant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

5-5-2023/masterpeace2/masterpeace2/Views/Resturants/Delete.cshtml
@model masterpeace2.Resturant

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdminDash.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Resturant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

5-5-2023/masterpeace2/masterpeace2/Views/Resturants/Edit.cshtml
@model masterpeace2.Resturant

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutRestDash.cshtml";
}

<h2>Edit</h2>


<div class="col-md-7 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">



            @using (Html.BeginForm("Edit", "Resturants", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                @*<div class="form-horizontal">*@
                <h4>Resturant</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ID)

                @*<div class="form-group">
                    @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.AspNetUser.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AspNetUser.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })*@
                        @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { type = "File", id = "Image", @class = "form-control" }})*@
                        <input type="file" name="ImageFile1" id="ImageFile1" onchange="previewImage(this, 'preview1')" />
                        <img id="preview1" style="display:none; height:100px; width:100px;" />
                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
                @*</div>*@
            }
            <script>
                function previewImage(input, previewId) {
                    if (input.files && input.files[0]) {
                        var reader = new FileReader();

                        reader.onload = function (e) {
                            $('#' + previewId)
                                .attr('src', e.target.result)
                                .show();
                        };

                        reader.readAsDataURL(input.files[0]);
                    }
                }
            </script>

            <div>

                @Html.ActionLink("Back to List", "ResInfo")
            </div>


        </div>
    </div>
</div>

5-5-2023/masterpeace2/masterpeace2/Views/Resturants/ResInfo.cshtml
@model masterpeace2.Resturant

@{
    ViewBag.Title = "resInfo";
    Layout = "~/Views/Shared/_LayoutRestDash.cshtml";
}



<style>
/*    body {
        margin: 0;
        padding-top: 40px;
        color: #2e323c;
        background: #f5f6fa;
        position: relative;
        height: 100%;
    }*/

    .account-settings .user-profile {
        margin: 0 0 1rem 0;
        padding-bottom: 1rem;
        text-align: center;
    }

        .account-settings .user-profile .user-avatar {
            margin: 0 0 1rem 0;
        }

            .account-settings .user-profile .user-avatar img {
                width: 90px;
                height: 90px;
                -webkit-border-radius: 100px;
                -moz-border-radius: 100px;
                border-radius: 100px;
            }

        .account-settings .user-profile h5.user-name {
            margin: 0 0 0.5rem 0;
        }

        .account-settings .user-profile h6.user-email {
            margin: 0;
            font-size: 0.8rem;
            font-weight: 400;
            color: #9fa8b9;
        }

    .account-settings .about {
        margin: 2rem 0 0 0;
        text-align: center;
    }

        .account-settings .about h5 {
            margin: 0 0 15px 0;
            color: #007ae1;
        }

        .account-settings .about p {
            font-size: 0.825rem;
        }

    .form-control {
        border: 1px solid #cfd1d8;
        -webkit-border-radius: 2px;
        -moz-border-radius: 2px;
        border-radius: 2px;
        font-size: .825rem;
        background: #ffffff;
        color: #2e323c;
    }
    .content-wrapper {
        background: #F4F5F7;
        padding: 1.5rem 1.5rem 1.5rem 1.5rem;
        width: 100%;
        -webkit-flex-grow: 1;
        flex-grow: 1;
    }

    .card {
        background: #ffffff;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        border: 0;
        margin-bottom: 1rem;
    }
</style>
<div class="container">
    <div class="row gutters">
        <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
            <div class="card h-100">
                <div class="card-body">
                    <div class="account-settings">
                        <div class="user-profile">
                            <div class="user-avatar">
                                @*<img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Maxwell Admin">*@
                                <img src="~/photos for masterpeace/@Model.Image" alt="Maxwell Admin">
                            </div>

                            <h5 class="user-name">Yuki Hayashi</h5>
                            <h6 class="user-email">yuki@Maxwell.com</h6>
                        </div>
                        <div class="about">
                            <h5>About</h5>
                            <p>I'm Yuki. Full Stack Designer I enjoy creating user-centric, delightful and human experiences.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
            <div class="card h-100">
                <div class="card-body">
                    <div class="row gutters">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <h6 class="mb-2 text-primary">Personal Details</h6>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="fullName">Full Name</label>
                                <input type="text" class="form-control" id="fullName" disabled value="@Model.Name" placeholder="Enter full name">
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="eMail">Email</label>
                                <input type="email" class="form-control" id="eMail" disabled value="@Model.AspNetUser.Email"  placeholder="Enter email ID">
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="phone">Phone</label>
                                <input type="text" class="form-control" id="phone" disabled value="@Model.PhoneNumber" placeholder="Enter phone number">
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="website">Address</label>
                                <input type="url" class="form-control" id="website" disabled value="@Model.Address" placeholder="Website url">
                            </div>
                        </div>
                    </div>
                    @*<div class="row gutters">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <h6 class="mt-3 mb-2 text-primary">Address</h6>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="Street">Street</label>
                                <input type="name" class="form-control" id="Street" placeholder="Enter Street">
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="ciTy">City</label>
                                <input type="name" class="form-control" id="ciTy" placeholder="Enter City">
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="sTate">State</label>
                                <input type="text" class="form-control" id="sTate" placeholder="Enter State">
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="form-group">
                                <label for="zIp">Zip Code</label>
                                <input type="text" class="form-control" id="zIp" placeholder="Zip Code">
                            </div>
                        </div>
                    </div>*@
                    <div class="row gutters">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <div class="text-right">
                                @*<button type="button" id="submit" name="submit" class="btn btn-secondary">Cancel</button>
                                <button type="button" id="submit" name="submit" class="btn btn-primary">Update</button>*@
                                @*@Html.ActionLink("Details", "Details", new { id = Model.ID, })*@
                                <a class="btn btn-outline-primary" href="@Url.Action("Edit", "Resturants", new { id = Model.ID})">
                                    Edit
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

5-5-2023/masterpeace2/masterpeace2/Views/Resturants/RestOrders.cshtml
@*@model IEnumerable<masterpeace2.Order>

@{
    //Layout = "~/Views/Shared/_LayoutRestDash.cshtml";
    Layout = "~/Views/Shared/_LayoutAdminDash.cshtml";
    ViewBag.Title = "RestOrders";
}*@

@model IEnumerable<masterpeace2.Order>

@{
    ViewBag.Title = "adminOrder";
    Layout = "~/Views/Shared/_LayoutRestDash.cshtml";
}



<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                ID
                            </th>
                            <th>
                                Customer
                            </th>
                            <th>
                                Date
                            </th>
                            <th>
                                Product
                            </th>
                            <th>
                                Resturant
                            </th>
                            <th>
                                Qty
                            </th>
                            <th>
                                Total Price
                            </th>
                            @*<th>
            Status
        </th>*@
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.OrderDate)
                                </td>

                                @*<img src="~/photos for masterpeace/@item.Category_Image" alt="@item.Category_Image" width="150" />*@
                                @{
                                    masterpeace2.masterpeaceEntities1 db = new masterpeace2.masterpeaceEntities1();

                                    var product = db.Products.Where(o => o.ID == item.ProductId).ToList();

                                    foreach (var item2 in product)
                                    {
                                        <td>
                                            <p>@item2.Product_Name</p>
                                        </td>
                                        <td>
                                            <p>@item2.Resturant.Name</p>
                                        </td>

                                    }}
                                @*@Html.DisplayFor(modelItem => item.ProductId.produc)*@

                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TotalPrice)
                                </td>
                                <td>
                                    <a class="btn btn-outline-primary" href="@Url.Action("AcceptOrders", "Resturants", new { id = item.ID})">
                                        Accept
                                    </a>
                                    <a class="btn btn-outline-danger" href="@Url.Action("RejectOrders", "Resturants", new { id = item.ID})">
                                        Reject
                                    </a>
                                </td>
                                @*<td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
        </td>*@
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>