5-5-2023/masterpeace2/masterpeace2/Controllers/AspNetUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using masterpeace2;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace masterpeace2.Controllers
{
    public class AspNetUsersController : Controller
    {
        private masterpeaceEntities1 db = new masterpeaceEntities1();

        // GET: AspNetUsers
        public ActionResult Index()
        {
            

            return View(db.AspNetUsers.ToList());
        }

        // GET: AspNetUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,FirstName,LastName")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetUser);
        }

        // GET: AspNetUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,FirstName,LastName")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        ////editing from user side>>>>>>>
        public ActionResult UserEdit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserEdit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,FirstName,LastName")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("UserProfile");
            }
            return View(aspNetUser);
        }                   

        //// End editing from user side>>>>>>>





        // POST: AspNetUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //public ActionResult UserProfile(string? id)
        //{
        //    //AspNetUser us = db.AspNetUsers.Find(id);
        //    var ID = User.Identity.GetUserId();
        //    var us = db.AspNetUsers.Where(a => a.Id == id);
        //    //var user = db.AspNetUsers;
        //    return View(us);
        //}
        //public ActionResult UserProfile(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    AspNetUser aspNetUser = db.AspNetUsers.Find(id);
        //    if (aspNetUser == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View("UserProfile", aspNetUser);
        //}
        public ActionResult UserProfile()
        {
            var id = User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        public ActionResult Orders(int? id)
        {
            
            var ID = User.Identity.GetUserId();           
            var order = db.Orders.Where(a => a.UserId == ID).ToList();
            return View("Orders", order);
        }

        public ActionResult dashrest(int? id)
        {

            var ID = User.Identity.GetUserId();
            var resturant = db.Resturants;
            return View("dashrest", resturant);
        }

        //public ActionResult dashrest(int? id)
        //{

        //    var ID = User.Identity.GetUserId();
        //    var resturant = db.Resturants;
        //    return View("dashrest", resturant);
        //}

        public ActionResult dashuser(int? id)
        {

            //var ID = User.Identity.GetUserId();
            var Users = db.AspNetUsers;
            return View("dashuser", Users);
        }

        public ActionResult adminOrder(int? id)
        {

            //var ID = User.Identity.GetUserId();
            var order = db.Orders;
            return View(order);
        }

        public ActionResult AcceptedOrders()
        {
            var id = User.Identity.GetUserId();
            //var products = db.Products.Include(p => p.Category).Include(p => p.Resturant).Where(p=>p.r);
            var orders = db.Orders.Where(p => p.IsAccepted == true);
            return View(orders.ToList());
        }

        public ActionResult Searchacc(string search)
        {
            //var x2 = db.Orders.Where(x => (x.Product.Product_Name.Contains(search) || x.FirstName.Contains(search) || x.LastName.Contains(search) /*|| x.OrderDate.ToString().Contains(search)*/)).ToList();
            var x2 = db.Orders.Where(x => (x.Product.Product_Name.Contains(search) || x.FirstName.Contains(search) || x.Product.Resturant.Name.Contains(search))).ToList();
            if (x2.Count() == 0)
            {
                return View("NotFound", x2);
            }
            else
            {
                return View("adminOrder", x2);
            }
            
        }
        public ActionResult SearchUser(string search)
        {
            var u = db.AspNetUsers.Where(x => (x.FirstName.Contains(search) || x.LastName.Contains(search) || x.Email.Contains(search))).ToList();

            if (u.Count() == 0)
            {
                return View("UserNotFound", u);
            }
            else
            {
                return View("dashuser",u);
            }
        }

    }
}

5-5-2023/masterpeace2/masterpeace2/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using masterpeace2;

namespace masterpeace2.Controllers
{
    public class OrdersController : Controller
    {
        private masterpeaceEntities1 db = new masterpeaceEntities1();

        // GET: Orders
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.AspNetUser).Include(o => o.Product);
            return View(orders.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.ProductId = new SelectList(db.Products, "ID", "Product_Name");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,UserId,ProductId,Quantity,TotalPrice,City,Address,PaymentMethod,OrderDate,FirstName,LastName,Phone,Email,IsAccepted,IsRejected,AcceptedTime")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", order.UserId);
            ViewBag.ProductId = new SelectList(db.Products, "ID", "Product_Name", order.ProductId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", order.UserId);
            ViewBag.ProductId = new SelectList(db.Products, "ID", "Product_Name", order.ProductId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserId,ProductId,Quantity,TotalPrice,City,Address,PaymentMethod,OrderDate,FirstName,LastName,Phone,Email,IsAccepted,IsRejected,AcceptedTime")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", order.UserId);
            ViewBag.ProductId = new SelectList(db.Products, "ID", "Product_Name", order.ProductId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

5-5-2023/masterpeace2/masterpeace2/Views/AspNetUsers/NotFound.cshtml
@{
    ViewBag.Title = "Notfound";
    Layout = "~/Views/Shared/_LayoutAdminDash.cshtml";
}


<div class="u-s-m-b-8">
    @*@using (Html.BeginForm("Searchacc", "Products", new { }, FormMethod.Post, new { @class = "my-form-class" }))*@
    @using (Html.BeginForm("Searchacc", "AspNetUsers"))
    {
        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" name="search" id="search" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="icon-search"></i></button>
                    </span>
                </div>
            </div>
        </div>
    }
</div>
<h2>No Results</h2>

5-5-2023/masterpeace2/masterpeace2/Views/AspNetUsers/UserNotFound.cshtml
@{
    ViewBag.Title = "UserNotFound";
    Layout = "~/Views/Shared/_LayoutAdminDash.cshtml";
}


<div class="u-s-m-b-8">
    @*@using (Html.BeginForm("Searchacc", "Products", new { }, FormMethod.Post, new { @class = "my-form-class" }))*@
    @using (Html.BeginForm("SearchUser", "AspNetUsers"))
    {
        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" name="search" id="search" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="icon-search"></i></button>
                    </span>
                </div>
            </div>
        </div>
    }
</div>
<h2>UserNotFound</h2>

5-5-2023/masterpeace2/masterpeace2/Views/AspNetUsers/adminOrder.cshtml
@model IEnumerable<masterpeace2.Order>

@{
    ViewBag.Title = "adminOrder";
    Layout = "~/Views/Shared/_LayoutAdminDash.cshtml";
}

@*<h2> Orders</h2>*@

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentMethod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.Product_Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PaymentMethod)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Product_Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>*@
<div class="u-s-m-b-8">
    @*@using (Html.BeginForm("Searchacc", "Products", new { }, FormMethod.Post, new { @class = "my-form-class" }))*@
    @using (Html.BeginForm("Searchacc", "AspNetUsers"))
    {
        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" name="search" id="search" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" style="padding:5px 20px 14px" type="submit"><i class="icon-search"></i></button>
                    </span>
                </div>
            </div>
        </div>
    }
</div>


<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Order ID
                            </th>
                            <th>
                                Customer Name
                            </th>
                            <th>
                                Date
                            </th>
                            <th>
                                Product
                            </th>
                            <th>
                                Resturant
                            </th>
                            <th>
                                Qty
                            </th>
                            <th>
                                Total Price
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.OrderDate)
                                </td>

                                @*<img src="~/photos for masterpeace/@item.Category_Image" alt="@item.Category_Image" width="150" />*@
                                @{
                                    masterpeace2.masterpeaceEntities1 db = new masterpeace2.masterpeaceEntities1();

                                    var product = db.Products.Where(o => o.ID == item.ProductId).ToList();

                                    foreach (var item2 in product)
                                    {
                                        <td>
                                            <p>@item2.Product_Name</p>
                                        </td>
                                        <td>
                                            <p>@item2.Resturant.Name</p>
                                        </td>

                                    }}
                                @*@Html.DisplayFor(modelItem => item.ProductId.produc)*@

                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TotalPrice)
                                </td>
                                @*<td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
        </td>*@
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

5-5-2023/masterpeace2/masterpeace2/Views/AspNetUsers/dashuser.cshtml
@model IEnumerable<masterpeace2.AspNetUser>

@{
    Layout = "~/Views/Shared/_LayoutAdminDash.cshtml";
}

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailConfirmed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PasswordHash)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SecurityStamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumberConfirmed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TwoFactorEnabled)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LockoutEndDateUtc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LockoutEnabled)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccessFailedCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>*@

<div class="u-s-m-b-8">
    @*@using (Html.BeginForm("Searchacc", "Products", new { }, FormMethod.Post, new { @class = "my-form-class" }))*@
    @using (Html.BeginForm("SearchUser", "AspNetUsers"))
    {
        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" name="search" id="search" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" style="padding:5px 20px 14px" type="submit"><i class="icon-search"></i></button>
                    </span>
                </div>
            </div>
        </div>
    }
</div>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            @*<th>
                                @Html.DisplayNameFor(model => model.EmailConfirmed)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PasswordHash)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SecurityStamp)
                            </th>*@
                            <th>
                                @Html.DisplayNameFor(model => model.PhoneNumber)
                            </th>
                            @*<th>
                                @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
                            </th*@
                            @*<th>
                                @Html.DisplayNameFor(model => model.TwoFactorEnabled)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LockoutEnabled)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.AccessFailedCount)
                            </th>*@
                            <th>
                                @Html.DisplayNameFor(model => model.UserName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LastName)
                            </th>
                            <th></th>
                        </tr>

                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                @*<td>
                                    @Html.DisplayFor(modelItem => item.EmailConfirmed)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PasswordHash)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SecurityStamp)
                                </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                                </td>
                                @*<td>
                                    @Html.DisplayFor(modelItem => item.PhoneNumberConfirmed)
                                </td>*@
                                @*<td>
                                    @Html.DisplayFor(modelItem => item.TwoFactorEnabled)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LockoutEndDateUtc)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LockoutEnabled)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.AccessFailedCount)
                                </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LastName)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>